# Generated by Django 5.1.6 on 2025-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
