# Generated by Django 5.1.6 on 2025-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employerprofile_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="{MEDIA_ROOT}/thumbnails/"
            ),
        ),
    ]
