# Generated by Django 5.1.6 on 2025-02-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_employerprofile_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
