# Generated by Django 5.1.6 on 2025-02-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_employerprofile_thumbnail"),
        ("board", "0009_benefit_remove_joblisting_benefits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, help_text="Skills you posess", to="board.skill"
            ),
        ),
    ]
