# Generated by Django 5.1.6 on 2025-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_jobseekerprofile_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
