# Generated by Django 5.1.6 on 2025-02-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_remove_joblisting_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="salary_max",
            field=models.IntegerField(
                blank=True, help_text="Maximum salary in USD", null=True
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="salary_min",
            field=models.IntegerField(
                blank=True, help_text="Minimum salary in USD", null=True
            ),
        ),
    ]
