# Generated by Django 5.1.6 on 2025-02-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_employerprofile_thumbnail"),
        ("board", "0007_jobcategory_joblisting_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="joblisting",
            name="application_instructions",
            field=models.TextField(
                blank=True,
                help_text="Instructions for applying (e.g., cover letter requirements)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="application_url",
            field=models.URLField(
                blank=True,
                help_text="External application link",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="benefits",
            field=models.JSONField(
                blank=True,
                help_text="List of benefits (e.g., health insurance, 401k)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="education_required",
            field=models.CharField(
                blank=True,
                help_text="E.g., Bachelor's degree, High school diploma",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                    ("Freelance", "Freelance"),
                ],
                default="Full-time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("Entry-level", "Entry-level"),
                    ("Mid-level", "Mid-level"),
                    ("Senior-level", "Senior-level"),
                    ("Executive", "Executive"),
                ],
                default="Entry-level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="hiring_process",
            field=models.TextField(
                blank=True, help_text="Description of interview process", null=True
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="remote_type",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Hybrid", "Hybrid"),
                    ("Remote", "Remote"),
                ],
                default="On-site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("Closed", "Closed"),
                    ("Draft", "Draft"),
                    ("Pending Approval", "Pending Approval"),
                ],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_listings",
                to="accounts.employerprofile",
            ),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="skills_required",
            field=models.ManyToManyField(
                blank=True, help_text="Required skills for the job", to="board.skill"
            ),
        ),
    ]
