# Generated by Django 5.1.6 on 2025-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_skill_joblisting_application_instructions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="benefits",
        ),
        migrations.AddField(
            model_name="joblisting",
            name="benefits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Benefits offered by the employer",
                to="board.benefit",
            ),
        ),
    ]
