# Generated by Django 5.1.6 on 2025-02-07 20:44

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="board.message",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=prose.fields.RichTextField(),
        ),
    ]
